rackn/digitalrebar-ux

- css/style.css
- js/dialog.js
- js/login.js
- js/provisioner.js
- views/dialogs/addbootenvdialog.tmpl.html
- views/dialogs/addtemplatedialog.tmpl.html
- views/login.html
- views/provisioner_bootenvs.html
- views/provisioner_machines.html
adding new bootenvs isn't fully tested but editing/PATCH works
> Bootenv editing and login enhancements

- views/nodes_singular.html
- views/provisioner_machines.html
nodes have a clickable machine uuid, hovering over the machine name yields the machine's uuid
> improved machine row style, added node link to machines

- js/networks.js
- js/nodes.js
- views/dialogs/addproviderdialog.tmpl.html
- views/networks.html
- views/networks_singular.html
- views/nodes.html
- views/nodes_singular.html
- views/provider.html
creates links to and editing ability of tenants on various pages (nodes, providers, networks)
> Tenant linking

- js/workloads.js
also prevents metal from being in non-metal workloads
> prevent non-metal from being included in metal exclusive workloads

- index.html
- js/app.js
- js/deployment_roles.js
- js/deployments.js
- js/dialog.js
- js/logging.js
- js/networks.js
- js/node_roles.js
- js/nodes.js
- js/provider.js
- js/rebar.js
- js/tenants.js
- views/logging.html
Lets a user search through errors (including the message, stack at time of error, and description), sort by type and date
> Logging Page

- js/rebar.js
Excess spam that wasn't necessary.
> Removed redundant handlers

- js/app.js
No more brief flashes of the signin page!
> instantaneous signin with revproxy

- index.html
- js/app.js
- js/lib/digest.js
- js/login.js
- views/login.html
It wasn't ever used and not using it broke things
> Remove "Remember me" checkbox

- js/app.js
- js/logging.js
> rename error backlog to alerts

- js/rebar.js
- views/deployments.html
> fix deployment role cohort sorting

- js/roles.js
- views/roles_singular.html
> Role metadata field

- index.html
- js/app.js
- js/lib/angular-clipboard.js
- js/node_roles.js
- views/node_roles_singular.html
> added copypaste to runlog and hide runlog card when not given

- css/style.css
- js/deployments.js
- views/deployments.html
> made deployment bars have status colors and icons

- js/deployments.js
- views/deployments.html
> updated icons and state names for deployments

- index.html
- js/api_helper.js
- js/app.js
- js/logging.js
- views/api_helper.html
> added api helper and made a new nav dropdown for it

- js/deployments.js
- views/deployment_roles_singular.html
- views/deployments.html
- views/nodes_singular.html
> Fix matrix role link and add buddy node roles to deployment roles

- css/style.css
- index.html
- js/app.js
- js/attribs.js
- js/dialog.js
- js/rebar.js
- views/api_helper.html
- views/attrib_render.tmpl.html
- views/attribs.html
- views/dialogs/editattribdialog.tmpl.html
bare bones list:
new edit buttons:
fancy editing magic:
> Attrib editing and list

- js/login.js
Previously. if a username and password were entered, the moment an endpoint became valid, a signin attempt was made. Now, this only happens if a user is already signed in
> fixed login on success issue

- js/app.js
- views/dialogs/addnodedialog.tmpl.html
> added fancy messages to node dialog

- index.html
- js/app.js
- js/rebar.js
> refresh button rotates when reloading data

- views/deployments.html
> remove the propose button from system deployments

- js/deployments.js
- views/deployments.html
> Service list

- build.sh
- css/style.css
- index.html
- js/app.js
- js/deployments.js
- views/deployments.html
It adds a graphical viewer to the deployments.
I'm still working on queries and views.
> This is funky and a work in progress.

- css/style.css
- js/deployments.js
- views/deployments.html
also fixes the weird random missing node role
> matrix now updates every 2 seconds, services are squares

- css/style.css
- js/workloads.js
- views/wizard/attributes.html
- views/wizard/deployment.html
- views/wizard/nodes.html
- views/wizard/os.html
- views/workloads.html
Still in development, just wanted to update the master branch
> new fancy wizard

- index.html
- js/app.js
- js/graphs.js
- views/graphs.html
Next up to add filter for each component type.
> Add a graph advanced option that can choose roles or node_roles.

- js/workloads.js
- views/wizard/nodes.html
- views/wizard/os.html
- views/wizard/overview.html
- views/workloads.html
> New wizard

- js/helper.js
- js/workloads.js
- views/wizard/done.html
- views/wizard/overview.html
- views/workloads.html
the overview page has an "Edit in API Call Helper Button"
> added final page, linked overview to api call helper

- css/style.css
- js/graphs.js
- views/graphs.html
> made graphs page fancier

- views/dialogs/addproviderdialog.tmpl.html
- views/provider.html
> image links open in new tab on provider pages

- js/workloads.js
- views/wizard/attributes.html
- views/wizard/deployment.html
- views/wizard/done.html
- views/wizard/nodes.html
- views/wizard/os.html
- views/wizard/overview.html
> Fix wizard node

- js/graphs.js
- views/graphs.html
> More graph selection

- js/dialog.js
- views/dialogs/addnodedialog.tmpl.html
> added export to api call helper button to node dialog

- js/app.js
- js/workloads.js
- views/wizard/attributes.html
- views/wizard/deployment.html
- views/wizard/nodes.html
- views/wizard/os.html
> changed the way workload deployments are selected and handled

- js/dialog.js
> Fix create and update nodes after the template hint

- js/workloads.js
handle case where you don't have providers but metal is OK
(and vice versa)
> handle case where both metal and cloud are enabled

- js/workloads.js
- views/wizard/os.html
This change adds a switch for the user to select, that makes the resulting logic much clearer in the function.
Added logic so that user can only pick from supported OS
Moved the order section after nodes for readability
Removed some dead code
Corrected Line Endings (created larger diff)
> Fix wizard to switch between metal and cloud 

- js/workloads.js
- views/wizard/attributes.html
- views/wizard/nodes.html
- views/wizard/overview.html
this simplifies the wizard code
the previous code had two paths for physical and created nodes
this pass makes those two paths simpler - both are generated when the wizard starts
then the correct set is chosen based on user choices 
the service role calculations were simplified also
Also, fixed the prefix generator
> major refactoring of wizard

- js/app.js
- js/deployment_roles.js
- js/dialog.js
- js/node_roles.js
- js/nodes.js
- js/roles.js
- views/attrib_render.tmpl.html
- views/dialogs/editattribdialog.tmpl.html
that is being modified.  this adds the target object to each attrib call in the shared code.
Basically, we add a new local (target) that includes the ID and type of the object.
Then we pass it into the system
> edit PUT attribute call MUST include the type of object 

- js/nodes.js
- views/nodes.html
- views/nodes_singular.html
The code was not correctly showing the "available" status, this patch wires that status into the node list correctly as an added state.
It also adds reserve (pause) and release (play) buttons to the node page.
> Fix Reserved Icons and Add Reserve/Release Buttons

- index.html
- js/app.js
- js/engine.js
- js/rebar.js
- views/engine.html
this is NOT very fancy, but it's a workable first pass to get the rules exposed from the UX.
> basic read-only rule engine view

- index.html
- js/app.js
- js/capabilities.js
- js/dialog.js
- js/users.js
- views/capabilities.html
- views/deployments.html
- views/dialogs/addtenantdialog.tmpl.html
- views/dialogs/adduserdialog.tmpl.html
- views/dialogs/editcapabilitiesdialog.tmpl.html
- views/tenants.html
- views/users.html
This requires core change to add the "dr-groups" capabilities and to PUT includes also.
The purpose of this change is to allow users to mange changes to capabilities groups and tune the tenant experience.
This allows us to tune the dr-groups capabilities.
At this time, there is NOT an add "user-defined" capabilities button.
> Capabilities Editing

- js/nodes.js
- views/nodes_singular.html
as requested by @galthaus, we don't need to have buttons for every power state.
> skip some power options

- js/provider.js
- views/dialogs/addproviderdialog.tmpl.html
- views/provider.html
> issue #269: providers do not allow blank names, enable delete

- js/workloads.js
- views/wizard/nodes.html
- views/wizard/os.html
resolves issue #275 
also makes it possible to move backwards with wizard and change deployments
added friendly notice in physical nodes about OS and source choice
As per request from @galthaus
>  allow user to pick non-system source pool

- js/workloads.js
- views/wizard/os.html
in a metal only case, the event was not getting called to build the node list.
> fix cannot select existing nodes bug

- js/workloads.js
> Variable missing $scope which works in dev mode (direct render), but

- index.html
- js/app.js
- js/dialog.js
- js/profile.js
- js/rebar.js
- views/dialogs/addprofiledialog.tmpl.html
- views/profiles.html
Still needs editing the profiles of nodes.
> Add initial profile construction with attribute editing.

- js/nodes.js
- views/nodes.html
rebased #287 - was easier to create a new pull
> move tenant and nodes are moved, switchable

- js/nodes.js
Fix bug causing networks to be repeated by refresh.
> Node Profile Edit

- js/dialog.js
- js/nodes.js
- views/dialogs/addnodedialog.tmpl.html
- views/dialogs/editnodedialog.tmpl.html
- views/nodes.html
- views/nodes_singular.html
refresh was causing the networks to accumulate incorrectly.
> fix network adding new items during update

- js/nodes.js
- views/nodes_singular.html
only shows if there is an ipmi-address set
requested by  @galthaus
> show bmc address if available on node status

- js/app.js
- js/barclamps.js
- js/dialog.js
- js/provisioner.js
- views/barclamps.html
- views/barclamps_singular.html
- views/dialogs/addtemplatedialog.tmpl.html
- views/provisioner_templates.html
> Barclamp upload

- js/networks.js
> fix network save/update issue.  issue #300

- js/bios_settings.js
- js/bios_updates.js
- views/bios_settings.html
- views/bios_updates.html
incremental progress on the bios settings page allows users to add new fields to existing sections 
and to delete field from existing sections.
next steps: add new section dialog
then port to other hardware subpages.
> allow users to add and remove values

- js/roles.js
- views/roles.html
- views/roles_singular.html
> fix role name issue #313

- js/barclamps.js
> use distinct names for workload and role

- js/graphs.js
- js/helper.js
- js/lib/angular-sparklines.js
- js/lib/jsontext.js
- js/login.js
- js/node_roles.js
changes $watch to $watchCollection
> Minor performance tweak

- js/deployments.js
- views/deployments.html
removed excess watchers and filters on deployments nodes and roles view
> Improved performance on Deployments view

- js/barclamps.js
- js/rebar.js
- js/roles.js
- views/roles_ansible_play.tmpl.html
body as an array is MUCH easier to read in the raw data.
modify the UX to consume and save data from that format.
> use new body format for barclamp save

- js/barclamps.js
- js/deployments.js
- views/deployments.html
- views/roles_ansible_play.tmpl.html
Matches patch to DR core that allows proposing system deployment.,
> allow propose of system deployment WITH WARNING

- js/barclamps.js
- views/barclamps.html
Fix #337 
Also remove redundant parent data from barclamps view
> fix bug #337 about name error

- js/nodes.js
- views/nodes_singular.html
> Node chassis serial number visible from node singular page

- js/deployments.js
- js/dialog.js
- views/deployments.html
> added deployment tenent changing

- views/attrib_render.tmpl.html
small hint helps when values are changed
> add default view to attribs

- views/dialogs/editnodedialog.tmpl.html
- views/nodes_singular.html
small changes to node edit dialog.
> tweaking layouts based on profiles testing

- js/deployments.js
- js/rebar.js
page loading because of errors that ignore when not compiled.
> Fix compile errors for missing items.  This prevents complete

- js/workloads.js
> Allow multiple control services and track their

- index.html
- js/app.js
- js/welcome.js
- views/deployments.html
- views/welcome.html
To reduce confusion for new users, create a landing page including a tutorial video.
We also removed some confusing extra navigation from the menu and deployment page.
> Create landing page for new users w/ Video Tour!

- js/nodes.js
I believe this issue was caused because var is required for the minifier.
Works for ux-dev, rev-proxy container needs to rebuilt.
From: https://github.com/digitalrebar/digitalrebar/issues/246
> missing var in addNode rawProfiles bug

- app/assets/views/wizard/os.html
> Disable the use-existing-nodes switch with no provisioner

- app/assets/views/nodes_singular.html
mouse is also a pointer over them now
> fix margin of node wrench buttons

- app/assets/views/nodes.html
> Allow more than one node to be selected in the node list view

- app/assets/views/components/fancylist.html
- app/assets/views/node_roles.html
- app/assets/views/nodes_singular.html
- app/assets/views/provider.html
- app/assets/views/roles_singular.html
- app/js/app.js
- app/js/nodes.js
- app/js/provider.js
- app/js/rebar.js
- app/js/roles.js
Reduces amount of code needed for views like these:
Also forces resource loading to be synchronous, so everything pulls in order when refresh is pushed
> List improvement

- app/js/graphs.js
- app/js/helper.js
- app/js/login.js
- app/js/node_roles.js
> Deregister watchers for graphs, helper, login, and noderoles

- app/assets/views/dialogs/addprofiledialog.tmpl.html
- app/assets/views/profiles.html
> Change orderBy to orderObjectBy in profiles

- app/assets/views/components/fancylist.html
- app/js/app.js
> Add table view to fancy list component

- app/assets/views/login.html
Looks more polished and is more intuitive
> Change the license switch to a checkbox

- app/js/bios_settings.js
- app/js/bios_updates.js
- app/js/deployments.js
This will fix a few dialogs that are broken at the moment
* Add Deployment
* BIOS Settings
* BIOS Updates
> Fix dialog promise confusion with $http promise

- app/assets/views/deployments.html
- app/assets/views/dialogs/editdeploymentdialog.tmpl.html
- app/js/bios_settings.js
- app/js/bios_updates.js
- app/js/deployments.js
> Deployment rename

- app/assets/views/dialogs/addprofiledialog.tmpl.html
- app/assets/views/profiles.html
- app/js/app.js
- app/js/profile.js
Profiles now correctly show names:
> Cleaner profiles

- app/assets/views/wizard/attributes.html
> Make advanced attribute dropdown fancier

- app/js/workloads.js
Issue was a scoping problem where `var node` happened to exist in a larger scope and this caused its value to change when a `var node` of a smaller scope changed :cry: thanks javascript
> Fix workloads node selection

- app/assets/views/dialogs/addnodedialog.tmpl.html
- app/js/deployments.js
- app/js/nodes.js
- app/js/provider.js
> Node provider note for missing providers

- app/assets/views/deployments.html
- app/js/deployments.js
- app/js/dialog.js
- app/js/rebar.js
Deployments look exactly the same, they are just more efficient now! Removed some bloat from the old deployments view. Also fixed an issue with node adding
> Deployment matrix

- app/css/style.css
> Fixed long role name cutoff in deployment matrix

- app/assets/views/logging.html
Helps the search find things like tenants, deployments, and providers by name
> Optimized Search for Pagination

- app/assets/views/wizard/nodes.html
- app/js/workloads.js
> Fix select issue with workloads nodes

- app/assets/views/deployments.html
https://github.com/digitalrebar/digitalrebar/issues/295
> Fix service and deployment role routes from deployment matrix

- app/js/app.js
> Removed outdated firmware menu from UX
