rackn/digitalrebar-ux

js/rebar.js
views/nodes.html

the new background css and node icons removed the ability for nodes to be displayed as off in the list

fix nodes statuses that should be off

---

js/login.js
views/login.html

added memory and autocomplete to host input on login, allow host to be put in url (?host=https://1.2.3.4)
hosts are cached when the query to api/license is successful

login host enhancements

---

views/workloads.html

an autocomplete input that defaults to default_os, allows you to type anything you want but gives hints towards os_support inside of the barclamp cfg_data

added provider os to workloads page

---

index.html
js/app.js
js/node_roles.js
views/node_roles_singular.html

when scrolling past the runlog, the node role toolbar will be fixed at the top of the screen

Node role static top

---

js/workloads.js

1. if more than one cloud provider is define and you choose not the
"first" one, the system fails.  The break was not populating a
complete map.
2. provider-create-hints doesn't work like thought.  So, it needs
to be found and added if not set.  This attempts to do that.

Fix two issues:

---

js/node_roles.js

a poll for an undefined object.  The API returns the error correctly,
but we should not spam.

Don't poll when something isn't selected.  This causes

---

index.html
js/app.js
js/dialog.js
js/node_roles.js
views/node_roles_singular.html

This pull correctly manages the node-role proposed workflow.  
If a user edits the attrib then the code will automatically put the node-role into a proposed state.
The user can then commit that node-role directly or do it from the deployment.
We also had to correct the status to include "proposed" status instead of reserved.  (it appears that reserved for nodes does NOT work at this time).
NOTE: minor change to fix Icon required updating the line-endings.  actual change is adding line 13.

Allow users to edit attributes for node-roles

---

views/nodes.html
views/nodes_singular.html

This makes it easier to jump to the website (assuming HTTPS) of a node.  
I'm assuming it's better to make this easier even if most nodes will 404 the address.

node address should be a HTTPS link

---

js/deployment_roles.js
js/deployments.js
js/dialog.js
js/nodes.js
js/rebar.js
views/deployment_roles_singular.html
views/deployments.html
views/node_roles_singular.html
views/nodes.html
views/nodes_singular.html
views/provider.html

This pull has two items.  
FIRST: While the deployment role attrib edit was working correctly, it was very confusing in the dialog.
The updated behavior will better highlight when the DR needs to be committed after things are edited.  If attribs are edited then the DR is automatically proposed (and the UX shows this clearly)
NOTE: we'll get the state from the API newly exposed DR.proposed property.  Hopefully, this code will "just work" now that the property is in the API.
SECOND: Refactor the way Node status & icons are being shown.  This simplifies the code and improves handling of power and reserved states.  It also takes advantage of the NEW node.icon ready values that can be user or role settable.
Also
1) used better Icon for redeploy.
2) added redeploy for deployment
3) hid delete & …

Provide correct feedback for Deployment Role Editing

---

index.html
views/deployments.html
views/tenants.html
views/users.html

As prep for making tenants work better, we need to expose more tenant info in the UX.

add tenant information to deployments, add icons everywhere

---

index.html
js/app.js
js/rebar.js
views/deployments.html

tweaks for usability - make the menus smaller as we add more stuff
also, node names were too long for cloud instances and it was making the matrix run off the screen.

group menus, shorten node name on matrix

---

LICENSE.rst
index.html
js/app.js
js/capabilities.js
js/dialog.js
js/nodes.js
js/workloads.js
views/capabilities.html
views/dialogs/addcapabilitydialog.tmpl.html
views/nodes_singular.html
views/wizard/os.html

This is relatively large pull, sorry....
Add a logout button (which just says there is no logout for now)
Allow users to add a key in the wizard (the API allows multiple, but we only offer 1 in the wizard)
Expand capability editing so we can tweak capabilities LIVE from the UX
Add Node Power buttons based on looking up the ACTUAL power states.

Wizard Keys, Power Buttons & Capabilities Editing

---

js/app.js
js/roles.js
js/workloads.js
views/deployment_roles.html
views/node_roles.html
views/roles.html
views/roles_singular.html

Cleanups including adding navigation buttons between node_roles and deployment_roles
Moved them off the advanced menu in favor of the higher level roles list.
The parents view requires the roles.requires patch on core.
TODO: Add attribs & wanted_attribs.

Improve Role view with parent/child and retry button.  

---

js/node_roles.js
views/node_roles_singular.html

does not require, but works with https://github.com/digitalrebar/doc/pull/153

add help link for node role failures

---

index.html
js/app.js
js/switches.js
views/switches.html

not in menus yet but accesssible from /switches
this will create fake data if the data is missing (e.g. VMs or cloud instances).
there are likely many edge cases that have to be handled; however this is enough to start testing and showing switch rendering.

add proto-type switch rendering code

---

js/workloads.js
views/wizard/nodes.html

for created nodes, put the add button back (assume they are workers)
for system nodes, allow user to update the list
Removing the deselect code fixed the double remove bug.
changes to HTML were small (mainly icons) but had to change line endings so diff is larger.

wizard add nodes, fix double deselect button

---

js/nodes.js
js/rebar.js
views/nodes_singular.html

Call the network_allocations API when getting node information
Present the allocations on the node view page
To render range information, we needed to get the ranges when we load networks.
Also, added aria labels trying to silence warnings from Angular.

add network interface and range information to node display

---

js/dialog.js
js/nodes.js
views/dialogs/addnodedialog.tmpl.html
views/dialogs/editnodedialog.tmpl.html
views/nodes.html
views/nodes_singular.html

This patch allows users to edit node name, description and profile for the first time!
It also adds profile to the node create options.
If fixes some variable naming in the dialog path
WARNING: The profile edit does NOT work due to an API issue - the change is submitted to the API but the profile is not updated.  This could be format or an API issue.

Add Profile Editing for Node (and profiles on create)

---

js/provider.js

needs to use the same syntax as the add from the nodes list.

correct missed _ when called from providers

---

index.html
js/app.js
js/rebar.js
views/annealer.html

for large systems, 15 second polling is overkill.  this allows the user to set the polling rate
AND it automatically will slow down for large systems too.

add user controllable polling rate for annealer

---

index.html
js/node_roles.js
js/rebar.js
views/annealer.html
views/node_roles_singular.html
views/nodes_singular.html
views/provider.html

Based on large system review, we were being way to aggressive with polling.
This change fixes the polling models (beyond the earlier pull that made them settable)
It also tells the UI to NOT send the large runlogs on routine updates
The runlog is retrieved ONLY when looking at the node_role page
The runlog is NOT stored in RAM to save the UX memory footprint
Also:
* cleaned up some aria labels that were causing log noise
* fixed the provider nodes rendering page

Performance Tune UX for polling & node roles runlog

---

js/node_roles.js
views/deployment_roles_singular.html
views/node_roles_singular.html

before this change, it was very difficult to find the deployment role information from the service roles.
also, it was potentially confusing for users the scope of the change they were making.
this change should help to clarify the scope of attribute changes.
it also removes the link to the phantom nodes for services roles.

improve clairity and links between node roles and deployment roles

---

js/rebar.js
js/roles.js
views/roles_ansible_play.tmpl.html
views/roles_script.tmpl.html
views/roles_singular.html

This is the first step to allowing different jig to render metadata helpers like we did for Script.

Role Metadata into templates based on script & ansible types

---

js/bios_updates.js

package is a keyword that fails when run with a strict
mode runner like chrome.

Convert variable package to mypackage because

---

js/node_roles.js
views/attrib_render.tmpl.html

link was broken.
this makes it easier to work with attributes that are [object] instead of showing values,

fix link for node_role attribs so that it does details via API helper

---

views/attrib_render.tmpl.html

the previous code would EXPAND defaults with hashes and maps in an ugly way.  This code will hide big defaults unless the user wants to see them.

do NOT expand defaults but allow user to expand

---

js/networks.js
views/networks_singular.html

As per @galthaus discussion, the default is false, false; however, new host or dhcp ranges will be fixed by the API when created.
I review the @Meshiest version of this patch and it is very similar.
NOTE: It requires the bug #184 to be fixed in core because the API does not currently allow updates to these fields.

Allow users to edit leases for network ranges

---

js/workloads.js

this check was preventing deployments from being selected for non-obvious reasons.  
it's not really required that deployments be proposed.

remove requirement that deployments are proposed

---

js/nodes.js
views/nodes_singular.html

This extends one of the three redeploy buttons with a list of OS that users can pick
This makes it much easier for users to change the OS of a node to one of the valid choices.
This model could be extended to the other buttons.
Also, fix @VictorLowther bug where the link button showed layered text.

from node page, expand redeploy to select OS

---

js/workloads.js

Don't use types for names of nodes because

---

app/assets/views/dialogs/editattribdialog.tmpl.html

Previously it would overflow, now it looks the same but functions better

Improve attribute editor dialog layout

---

app/assets/views/provider.html

Angular 1.6 introduced something that caused ng-value to happen before ng-model which overrode the stored value (provider.auth_details[name])

Fix provider auth details not showing up

---

app/assets/views/deployments.html

When refactoring to use the optimized view, the wrong link target was chosen.
This corrects that change.
Fixes bug #415

BUG services should link to the node_role
